# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _z01
else:
    import _z01

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _z01.delete_SwigPyIterator

    def value(self):
        return _z01.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _z01.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _z01.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _z01.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _z01.SwigPyIterator_equal(self, x)

    def copy(self):
        return _z01.SwigPyIterator_copy(self)

    def next(self):
        return _z01.SwigPyIterator_next(self)

    def __next__(self):
        return _z01.SwigPyIterator___next__(self)

    def previous(self):
        return _z01.SwigPyIterator_previous(self)

    def advance(self, n):
        return _z01.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _z01.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _z01.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _z01.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _z01.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _z01.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _z01.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _z01:
_z01.SwigPyIterator_swigregister(SwigPyIterator)

class vectori(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _z01.vectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _z01.vectori___nonzero__(self)

    def __bool__(self):
        return _z01.vectori___bool__(self)

    def __len__(self):
        return _z01.vectori___len__(self)

    def __getslice__(self, i, j):
        return _z01.vectori___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _z01.vectori___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _z01.vectori___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _z01.vectori___delitem__(self, *args)

    def __getitem__(self, *args):
        return _z01.vectori___getitem__(self, *args)

    def __setitem__(self, *args):
        return _z01.vectori___setitem__(self, *args)

    def pop(self):
        return _z01.vectori_pop(self)

    def append(self, x):
        return _z01.vectori_append(self, x)

    def empty(self):
        return _z01.vectori_empty(self)

    def size(self):
        return _z01.vectori_size(self)

    def swap(self, v):
        return _z01.vectori_swap(self, v)

    def begin(self):
        return _z01.vectori_begin(self)

    def end(self):
        return _z01.vectori_end(self)

    def rbegin(self):
        return _z01.vectori_rbegin(self)

    def rend(self):
        return _z01.vectori_rend(self)

    def clear(self):
        return _z01.vectori_clear(self)

    def get_allocator(self):
        return _z01.vectori_get_allocator(self)

    def pop_back(self):
        return _z01.vectori_pop_back(self)

    def erase(self, *args):
        return _z01.vectori_erase(self, *args)

    def __init__(self, *args):
        _z01.vectori_swiginit(self, _z01.new_vectori(*args))

    def push_back(self, x):
        return _z01.vectori_push_back(self, x)

    def front(self):
        return _z01.vectori_front(self)

    def back(self):
        return _z01.vectori_back(self)

    def assign(self, n, x):
        return _z01.vectori_assign(self, n, x)

    def resize(self, *args):
        return _z01.vectori_resize(self, *args)

    def insert(self, *args):
        return _z01.vectori_insert(self, *args)

    def reserve(self, n):
        return _z01.vectori_reserve(self, n)

    def capacity(self):
        return _z01.vectori_capacity(self)
    __swig_destroy__ = _z01.delete_vectori

# Register vectori in _z01:
_z01.vectori_swigregister(vectori)

class vectord(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _z01.vectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _z01.vectord___nonzero__(self)

    def __bool__(self):
        return _z01.vectord___bool__(self)

    def __len__(self):
        return _z01.vectord___len__(self)

    def __getslice__(self, i, j):
        return _z01.vectord___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _z01.vectord___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _z01.vectord___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _z01.vectord___delitem__(self, *args)

    def __getitem__(self, *args):
        return _z01.vectord___getitem__(self, *args)

    def __setitem__(self, *args):
        return _z01.vectord___setitem__(self, *args)

    def pop(self):
        return _z01.vectord_pop(self)

    def append(self, x):
        return _z01.vectord_append(self, x)

    def empty(self):
        return _z01.vectord_empty(self)

    def size(self):
        return _z01.vectord_size(self)

    def swap(self, v):
        return _z01.vectord_swap(self, v)

    def begin(self):
        return _z01.vectord_begin(self)

    def end(self):
        return _z01.vectord_end(self)

    def rbegin(self):
        return _z01.vectord_rbegin(self)

    def rend(self):
        return _z01.vectord_rend(self)

    def clear(self):
        return _z01.vectord_clear(self)

    def get_allocator(self):
        return _z01.vectord_get_allocator(self)

    def pop_back(self):
        return _z01.vectord_pop_back(self)

    def erase(self, *args):
        return _z01.vectord_erase(self, *args)

    def __init__(self, *args):
        _z01.vectord_swiginit(self, _z01.new_vectord(*args))

    def push_back(self, x):
        return _z01.vectord_push_back(self, x)

    def front(self):
        return _z01.vectord_front(self)

    def back(self):
        return _z01.vectord_back(self)

    def assign(self, n, x):
        return _z01.vectord_assign(self, n, x)

    def resize(self, *args):
        return _z01.vectord_resize(self, *args)

    def insert(self, *args):
        return _z01.vectord_insert(self, *args)

    def reserve(self, n):
        return _z01.vectord_reserve(self, n)

    def capacity(self):
        return _z01.vectord_capacity(self)
    __swig_destroy__ = _z01.delete_vectord

# Register vectord in _z01:
_z01.vectord_swigregister(vectord)

class vectori2d(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _z01.vectori2d_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _z01.vectori2d___nonzero__(self)

    def __bool__(self):
        return _z01.vectori2d___bool__(self)

    def __len__(self):
        return _z01.vectori2d___len__(self)

    def __getslice__(self, i, j):
        return _z01.vectori2d___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _z01.vectori2d___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _z01.vectori2d___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _z01.vectori2d___delitem__(self, *args)

    def __getitem__(self, *args):
        return _z01.vectori2d___getitem__(self, *args)

    def __setitem__(self, *args):
        return _z01.vectori2d___setitem__(self, *args)

    def pop(self):
        return _z01.vectori2d_pop(self)

    def append(self, x):
        return _z01.vectori2d_append(self, x)

    def empty(self):
        return _z01.vectori2d_empty(self)

    def size(self):
        return _z01.vectori2d_size(self)

    def swap(self, v):
        return _z01.vectori2d_swap(self, v)

    def begin(self):
        return _z01.vectori2d_begin(self)

    def end(self):
        return _z01.vectori2d_end(self)

    def rbegin(self):
        return _z01.vectori2d_rbegin(self)

    def rend(self):
        return _z01.vectori2d_rend(self)

    def clear(self):
        return _z01.vectori2d_clear(self)

    def get_allocator(self):
        return _z01.vectori2d_get_allocator(self)

    def pop_back(self):
        return _z01.vectori2d_pop_back(self)

    def erase(self, *args):
        return _z01.vectori2d_erase(self, *args)

    def __init__(self, *args):
        _z01.vectori2d_swiginit(self, _z01.new_vectori2d(*args))

    def push_back(self, x):
        return _z01.vectori2d_push_back(self, x)

    def front(self):
        return _z01.vectori2d_front(self)

    def back(self):
        return _z01.vectori2d_back(self)

    def assign(self, n, x):
        return _z01.vectori2d_assign(self, n, x)

    def resize(self, *args):
        return _z01.vectori2d_resize(self, *args)

    def insert(self, *args):
        return _z01.vectori2d_insert(self, *args)

    def reserve(self, n):
        return _z01.vectori2d_reserve(self, n)

    def capacity(self):
        return _z01.vectori2d_capacity(self)
    __swig_destroy__ = _z01.delete_vectori2d

# Register vectori2d in _z01:
_z01.vectori2d_swigregister(vectori2d)

class vectori3d(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _z01.vectori3d_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _z01.vectori3d___nonzero__(self)

    def __bool__(self):
        return _z01.vectori3d___bool__(self)

    def __len__(self):
        return _z01.vectori3d___len__(self)

    def __getslice__(self, i, j):
        return _z01.vectori3d___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _z01.vectori3d___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _z01.vectori3d___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _z01.vectori3d___delitem__(self, *args)

    def __getitem__(self, *args):
        return _z01.vectori3d___getitem__(self, *args)

    def __setitem__(self, *args):
        return _z01.vectori3d___setitem__(self, *args)

    def pop(self):
        return _z01.vectori3d_pop(self)

    def append(self, x):
        return _z01.vectori3d_append(self, x)

    def empty(self):
        return _z01.vectori3d_empty(self)

    def size(self):
        return _z01.vectori3d_size(self)

    def swap(self, v):
        return _z01.vectori3d_swap(self, v)

    def begin(self):
        return _z01.vectori3d_begin(self)

    def end(self):
        return _z01.vectori3d_end(self)

    def rbegin(self):
        return _z01.vectori3d_rbegin(self)

    def rend(self):
        return _z01.vectori3d_rend(self)

    def clear(self):
        return _z01.vectori3d_clear(self)

    def get_allocator(self):
        return _z01.vectori3d_get_allocator(self)

    def pop_back(self):
        return _z01.vectori3d_pop_back(self)

    def erase(self, *args):
        return _z01.vectori3d_erase(self, *args)

    def __init__(self, *args):
        _z01.vectori3d_swiginit(self, _z01.new_vectori3d(*args))

    def push_back(self, x):
        return _z01.vectori3d_push_back(self, x)

    def front(self):
        return _z01.vectori3d_front(self)

    def back(self):
        return _z01.vectori3d_back(self)

    def assign(self, n, x):
        return _z01.vectori3d_assign(self, n, x)

    def resize(self, *args):
        return _z01.vectori3d_resize(self, *args)

    def insert(self, *args):
        return _z01.vectori3d_insert(self, *args)

    def reserve(self, n):
        return _z01.vectori3d_reserve(self, n)

    def capacity(self):
        return _z01.vectori3d_capacity(self)
    __swig_destroy__ = _z01.delete_vectori3d

# Register vectori3d in _z01:
_z01.vectori3d_swigregister(vectori3d)


def extract_z01(data3d):
    return _z01.extract_z01(data3d)


